### ISSUE TITLE
Running greed fails with `assert w3.is_connected()`

### ISSUE THREAD

**Issue by RaoulSchaffranek** [ucsb-seclab/greed#15]
I just installed `greed` and tried running it on a sample contract.

The installation instructions were clear, and the setup worked like a charm; the only hiccup was changing `analyze_hex.sh contract.hex` to `analyze_hex.sh --file contract.hex`.

But when running `greed` I get the following python stacktrace:

~~~bash
$ greed ./greed/ --debug
DEBUG | greed.project | All sanity checks passed in 0.0001s
Traceback (most recent call last):
  File "/home/raoul/.virtualenvs/greed/bin/greed", line 122, in <module>
    main(args)
  File "/home/raoul/.virtualenvs/greed/bin/greed", line 33, in main
    assert w3.is_connected()
AssertionError
~~~

I'm a little stuck here. Any ideas?

**Comment by ruaronicola** [comment]
Hi Raoul,

I have addressed this in the latest commit (`b61c81bd`). 

The reason you see that error is that for some of our analysis (mostly in `memory/partial_concrete_storage.py`) we use a web3 endpoint to read on-chain data. This is not really needed in the script you are using so making it optional seems a good idea. Thanks for reporting this!

**Comment by degrigis** [comment]
It seems a good idea to also add a warning in the partial concrete storage instead of crashing. Will add this :)

**Comment by RaoulSchaffranek** [comment]
That was quick 🚀 I can confirm the error is gone, thanks guys!
